=== Anton94/XML-and-ASP-programming/ASP.NET project/xmlToSql/xmlToSql/resources/RoboSim.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT RoboSimulation (SimulationName, SimulationOwner, SimulationOwnerEmail, Environments, Robots, Maps, Algorithms)>
    <!ATTLIST RoboSimulation id ID #REQUIRED >
    <!ELEMENT SimulationName (#PCDATA)>
    <!ELEMENT SimulationOwner (#PCDATA)>
    <!ELEMENT SimulationOwnerEmail (#PCDATA)>
    <!ELEMENT  Environments (Environment*)>
        <!ELEMENT Environment (TravelCostEnter, TravelCostIn, TravelCostExit, Damage)>
            <!ATTLIST Environment id ID #REQUIRED
                                  name CDATA #REQUIRED>
            <!ELEMENT TravelCostEnter (#PCDATA)>
            <!ELEMENT TravelCostIn (#PCDATA)>
            <!ELEMENT TravelCostExit (#PCDATA)>
            <!ELEMENT Damage (#PCDATA)>
    <!ELEMENT Robots (Robot*)>
        <!ELEMENT Robot (RobotMeshGrid, Speed, SpeedBack, TurningSpeed, TurningSpeedBack, Wheels?, Sensors?, Rotors?)>
            <!ATTLIST Robot id ID #REQUIRED
                            environments IDREFS #REQUIRED
                            name CDATA #REQUIRED
                            owner CDATA #REQUIRED>
            <!ELEMENT RobotMeshGrid (#PCDATA)>
            <!ELEMENT Speed (#PCDATA)>
            <!ELEMENT SpeedBack (#PCDATA)>
            <!ELEMENT TurningSpeed (#PCDATA)>
            <!ELEMENT TurningSpeedBack (#PCDATA)>            
            <!ELEMENT Wheels (Wheel*)>          
                <!ELEMENT Wheel (WheelMeshGrid, WheelDiameter, WheelWidth)>
                    <!ATTLIST Wheel driving (ДА|НЕ) #REQUIRED>
                    <!ELEMENT WheelMeshGrid (#PCDATA)>
                    <!ELEMENT WheelDiameter (#PCDATA)>
                    <!ELEMENT WheelWidth (#PCDATA)>
            <!ELEMENT Sensors (Sensor*)>
                <!ELEMENT Sensor (SensorMeshGrid, NumberOfValusPerSecond)>
                    <!ATTLIST Sensor name CDATA #REQUIRED
                                     valueType CDATA #REQUIRED>
                    <!ELEMENT SensorMeshGrid (#PCDATA)>
                    <!ELEMENT NumberOfValusPerSecond (#PCDATA)>
            <!ELEMENT Rotors (Rotor*)>
                <!ELEMENT Rotor (RotorMeshGrid, RotorLiftingPower)>
                    <!ELEMENT RotorMeshGrid (#PCDATA)>
                    <!ELEMENT RotorLiftingPower (#PCDATA)>
    <!ELEMENT Maps (Map*)>
        <!ELEMENT Map (MapData, Denivelation)>
            <!ATTLIST Map id ID #REQUIRED
                          environments IDREFS #REQUIRED>
            <!ELEMENT MapData (#PCDATA)>
            <!ELEMENT Denivelation (#PCDATA)>
    <!ELEMENT Algorithms (Algorithm*)>
        <!ELEMENT Algorithm (Complexity, Depth)>
            <!ATTLIST Algorithm id ID #REQUIRED
                                name CDATA #REQUIRED 
                                diffEnvironments (ДА|НЕ) #REQUIRED
                                multipleDestPoints (ДА|НЕ) #REQUIRED>
            <!ELEMENT Complexity (#PCDATA)>
            <!ELEMENT Depth (#PCDATA)>

=== Anton94/XML-and-ASP-programming/ASP.NET project/xmlToSql/xmlToSql/resources/ValidXMLDocument-18.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RoboSimulation SYSTEM "RoboSim.dtd">
<RoboSimulation id="S0" name="Симулация 18" owner="Петран">
    <SimulationOwnerEmail>petran@gmail.com</SimulationOwnerEmail>
    <SimulationDescription>Описание на симулация 18</SimulationDescription>
    <SimulationRating>4.89</SimulationRating>
    <Environments>
        <Environment id="IDE000" name="Вода">
            <TravelCostEnter>1.0</TravelCostEnter>
            <TravelCostIn>1.0</TravelCostIn>
            <TravelCostExit>1.5</TravelCostExit>
            <Damage>3.5</Damage>
        </Environment>
        <Environment id="IDE001" name="Блато">
            <TravelCostEnter>1.0</TravelCostEnter>
            <TravelCostIn>2.0</TravelCostIn>
            <TravelCostExit>3.5</TravelCostExit>
            <Damage>6.5</Damage>
        </Environment>         
        <Environment id="IDE002" name="Земя">
            <TravelCostEnter>0.0</TravelCostEnter>
            <TravelCostIn>0.0</TravelCostIn>
            <TravelCostExit>0.5</TravelCostExit>
            <Damage>1.5</Damage>
        </Environment>  
    </Environments>
    
    <Robots>
        <Robot id="IDR000" name="Робо 008" owner="Сиси">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>28.6</Speed>
            <SpeedBack>28.4</SpeedBack>
            <TurningSpeed>24.4</TurningSpeed>
            <TurningSpeedBack>24.4</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>13.5</WheelDiameter>
                    <WheelWidth>21.7</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>13.5</WheelDiameter>
                    <WheelWidth>21.7</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>13.0</WheelDiameter>
                    <WheelWidth>11.7</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh3.obj</WheelMeshGrid>
                    <WheelDiameter>13.0</WheelDiameter>
                    <WheelWidth>11.7</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>16</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>3.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>3.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh2.obj</RotorMeshGrid>
                    <RotorLiftingPower>6.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh3.obj</RotorMeshGrid>
                    <RotorLiftingPower>6.0</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>
        <Robot id="IDR001" name="Робо 009" owner="Марги">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>15.0</Speed>
            <SpeedBack>15.4</SpeedBack>
            <TurningSpeed>15.0</TurningSpeed>
            <TurningSpeedBack>15.3</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>12.5</WheelDiameter>
                    <WheelWidth>10.3</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>12.5</WheelDiameter>
                    <WheelWidth>10.3</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>13.0</WheelDiameter>
                    <WheelWidth>10.3</WheelWidth>
                </Wheel>
            </Wheels>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>30.0</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>
        <Robot id="IDR002" name="Робо 010" owner="Бианка">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>19.0</Speed>
            <SpeedBack>18.6</SpeedBack>
            <TurningSpeed>17.7</TurningSpeed>
            <TurningSpeedBack>17.4</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>13.7</WheelDiameter>
                    <WheelWidth>10.9</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>3.7</WheelDiameter>
                    <WheelWidth>10.9</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>1.7</WheelDiameter>
                    <WheelWidth>10.9</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh3.obj</WheelMeshGrid>
                    <WheelDiameter>1.7</WheelDiameter>
                    <WheelWidth>10.9</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>6</NumberOfValusPerSecond>
                </Sensor>
                <Sensor name="Сензор за измерване на звука" valueType="звук">
                    <SensorMeshGrid>distSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>5</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>4.6</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>4.6</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>
    </Robots>
    
    <Maps>
        <Map id="IDM000" name="Карта 1">
            <MapData>map000.bin</MapData>
            <Denivelation>4</Denivelation>
        </Map>
        <Map id="IDM001" name="Карта 2">
            <MapData>map001.bin</MapData>
            <Denivelation>0</Denivelation>
        </Map>
        <Map id="IDM002" name="Карта 3">
            <MapData>map002.bin</MapData>
            <Denivelation>10</Denivelation>
        </Map>
        <Map id="IDM003" name="Карта 4">
            <MapData>map003.bin</MapData>
            <Denivelation>0</Denivelation>
        </Map>
    </Maps>
    
    <Algorithms>
        <Algorithm id="IDA000" name="Търсене в дълбочина" diffEnvironments="НЕ" multipleDestPoints="ДА">
            <Complexity>Линейна</Complexity>
            <Depth>25</Depth>
        </Algorithm> 
        <Algorithm id="IDA001" name="Най-бързото спускане" diffEnvironments="НЕ" multipleDestPoints="НЕ">
            <Complexity>Линейно по пътя с евристика</Complexity>
            <Depth>25</Depth>
        </Algorithm>      
    </Algorithms>
</RoboSimulation>

=== Anton94/XML-and-ASP-programming/ASP.NET project/xmlToSql/xmlToSql/resources/ValidXMLDocument-7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RoboSimulation SYSTEM "RoboSim.dtd">
<RoboSimulation id="S0">
    <SimulationName>Симулация 7</SimulationName>
    <SimulationOwner>Мирела</SimulationOwner>
    <SimulationOwnerEmail>antonvdudov@gmail.com</SimulationOwnerEmail>
    <Environments>
        <Environment id="IDE000" name="Земя">
            <TravelCostEnter>1.0</TravelCostEnter>
            <TravelCostIn>1.0</TravelCostIn>
            <TravelCostExit>2.0</TravelCostExit>
            <Damage>0.0</Damage>
        </Environment>
        <Environment id="IDE001" name="Вода">
            <TravelCostEnter>1.6</TravelCostEnter>
            <TravelCostIn>3.1</TravelCostIn>
            <TravelCostExit>1.8</TravelCostExit>
            <Damage>1.5</Damage>
        </Environment>
        <Environment id="IDE002" name="Въздух">
            <TravelCostEnter>2.2</TravelCostEnter>
            <TravelCostIn>1.6</TravelCostIn>
            <TravelCostExit>1.0</TravelCostExit>
            <Damage>0.0</Damage>
        </Environment>     
    </Environments>
    
    <Robots>
        <Robot id="IDR000" environments="IDE000 IDE001" name="Робо ДВ40" owner="Петър">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>17.0</Speed>
            <SpeedBack>16.3</SpeedBack>
            <TurningSpeed>18.0</TurningSpeed>
            <TurningSpeedBack>18.2</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>2.5</WheelDiameter>
                    <WheelWidth>1.0</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>2.5</WheelDiameter>
                    <WheelWidth>1.0</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>3.0</WheelDiameter>
                    <WheelWidth>1.0</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>7</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
        </Robot>        
        <Robot id="IDR001" environments="IDE000 IDE002" name="Робо КЛМ000" owner="Борка">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>19.0</Speed>
            <SpeedBack>19.3</SpeedBack>
            <TurningSpeed>13.5</TurningSpeed>
            <TurningSpeedBack>13.2</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>6.0</WheelDiameter>
                    <WheelWidth>1.2</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>3.8</WheelDiameter>
                    <WheelWidth>1.6</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>3.8</WheelDiameter>
                    <WheelWidth>1.6</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>2</NumberOfValusPerSecond>
                </Sensor>
                <Sensor name="Сензор за измерване на разстоянието" valueType="разстояние">
                    <SensorMeshGrid>distSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>4</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>2.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>2.0</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>        
        <Robot id="IDR002" environments="IDE000 IDE001 IDE002" name="Робо МС540" owner="Силвестър">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>24.2</Speed>
            <SpeedBack>24.1</SpeedBack>
            <TurningSpeed>24.0</TurningSpeed>
            <TurningSpeedBack>24.6</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>6.0</WheelDiameter>
                    <WheelWidth>1.5</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>6.0</WheelDiameter>
                    <WheelWidth>1.5</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>4.0</WheelDiameter>
                    <WheelWidth>1.1</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh3.obj</WheelMeshGrid>
                    <WheelDiameter>4.0</WheelDiameter>
                    <WheelWidth>1.1</WheelWidth>
                </Wheel>
            </Wheels>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>21.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>21.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh2.obj</RotorMeshGrid>
                    <RotorLiftingPower>11.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh3.obj</RotorMeshGrid>
                    <RotorLiftingPower>11.0</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>     
    </Robots>
    
    <Maps>
        <Map id="IDM000" environments="IDE000 IDE001 IDE002">
            <MapData>map000.bin</MapData>
            <Denivelation>0</Denivelation>
        </Map>
    </Maps>
    
    <Algorithms>
        <Algorithm id="IDA000" name="А звезда" diffEnvironments="ДА" multipleDestPoints="ДА">
            <Complexity>Зависи от евристиката</Complexity>
            <Depth>27</Depth>
        </Algorithm>  
    </Algorithms>
</RoboSimulation>

=== Anton94/XML-and-ASP-programming/ASP.NET project/ValidXMLDocument-13.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RoboSimulation SYSTEM "RoboSim.dtd">
<RoboSimulation>
    <SimulationName>Симулация 13</SimulationName>
    <SimulationOwner>Васил</SimulationOwner>
    <SimulationOwnerEmail>vasil@gmail.com</SimulationOwnerEmail>
    <Environments>
        <Environment id="IDE000" name="Вода">
            <TravelCostEnter>1.0</TravelCostEnter>
            <TravelCostIn>2.0</TravelCostIn>
            <TravelCostExit>1.3</TravelCostExit>
            <Damage>1.5</Damage>
        </Environment>     
        <Environment id="IDE001" name="Земя">
            <TravelCostEnter>1.3</TravelCostEnter>
            <TravelCostIn>1.1</TravelCostIn>
            <TravelCostExit>1.3</TravelCostExit>
            <Damage>0.3</Damage>
        </Environment>   
    </Environments>
    
    <Robots>
        <Robot id="IDR000" environments="IDE000 IDE001" name="Робо Е200" owner="Чарли">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>16.6</Speed>
            <SpeedBack>15.4</SpeedBack>
            <TurningSpeed>18.5</TurningSpeed>
            <TurningSpeedBack>12.5</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>5.5</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>6.0</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>6.0</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>2</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>6.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>6.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh2.obj</RotorMeshGrid>
                    <RotorLiftingPower>6.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh3.obj</RotorMeshGrid>
                    <RotorLiftingPower>6.0</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>
        <Robot id="IDR001" environments="IDE000 IDE001" name="Робо ЕВ233" owner="Наско">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>13.1</Speed>
            <SpeedBack>13.6</SpeedBack>
            <TurningSpeed>12.1</TurningSpeed>
            <TurningSpeedBack>12.2</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>4.5</WheelDiameter>
                    <WheelWidth>2.7</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>4.5</WheelDiameter>
                    <WheelWidth>2.7</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>5.5</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh3.obj</WheelMeshGrid>
                    <WheelDiameter>5.5</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
            </Wheels>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>14.3</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>14.3</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh2.obj</RotorMeshGrid>
                    <RotorLiftingPower>14.3</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>
        <Robot id="IDR002" environments="IDE001" name="Робо МК20" owner="Ваньо">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>19.0</Speed>
            <SpeedBack>18.6</SpeedBack>
            <TurningSpeed>25.0</TurningSpeed>
            <TurningSpeedBack>25.4</TurningSpeedBack>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>6</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>14.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>14.0</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>
    </Robots>
    
    <Maps>
        <Map id="IDM000" environments="IDE000 IDE001">
            <MapData>map000.bin</MapData>
            <Denivelation>4</Denivelation>
        </Map>
        <Map id="IDM001" environments="IDE001">
            <MapData>map001.bin</MapData>
            <Denivelation>0</Denivelation>
        </Map>
    </Maps>
    
    <Algorithms>
        <Algorithm id="IDA000" name="Търсене в дълбочина" diffEnvironments="НЕ" multipleDestPoints="ДА">
            <Complexity>Линейна</Complexity>
            <Depth>21</Depth>
        </Algorithm> 
        <Algorithm id="IDA001" name="Най-бързото спускане" diffEnvironments="НЕ" multipleDestPoints="НЕ">
            <Complexity>Линейно по пътя с евристика</Complexity>
            <Depth>Нелимитирано</Depth>
        </Algorithm>   
    </Algorithms>
</RoboSimulation>
