=== Anton94/XML-and-ASP-programming/ASP.NET project/xmlToSql/xmlToSql/resources/RoboSim.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT RoboSimulation (SimulationName, SimulationOwner, SimulationOwnerEmail, Environments, Robots, Maps, Algorithms)>
    <!ATTLIST RoboSimulation id ID #REQUIRED >
    <!ELEMENT SimulationName (#PCDATA)>
    <!ELEMENT SimulationOwner (#PCDATA)>
    <!ELEMENT SimulationOwnerEmail (#PCDATA)>
    <!ELEMENT  Environments (Environment*)>
        <!ELEMENT Environment (TravelCostEnter, TravelCostIn, TravelCostExit, Damage)>
            <!ATTLIST Environment id ID #REQUIRED
                                  name CDATA #REQUIRED>
            <!ELEMENT TravelCostEnter (#PCDATA)>
            <!ELEMENT TravelCostIn (#PCDATA)>
            <!ELEMENT TravelCostExit (#PCDATA)>
            <!ELEMENT Damage (#PCDATA)>
    <!ELEMENT Robots (Robot*)>
        <!ELEMENT Robot (RobotMeshGrid, Speed, SpeedBack, TurningSpeed, TurningSpeedBack, Wheels?, Sensors?, Rotors?)>
            <!ATTLIST Robot id ID #REQUIRED
                            environments IDREFS #REQUIRED
                            name CDATA #REQUIRED
                            owner CDATA #REQUIRED>
            <!ELEMENT RobotMeshGrid (#PCDATA)>
            <!ELEMENT Speed (#PCDATA)>
            <!ELEMENT SpeedBack (#PCDATA)>
            <!ELEMENT TurningSpeed (#PCDATA)>
            <!ELEMENT TurningSpeedBack (#PCDATA)>            
            <!ELEMENT Wheels (Wheel*)>          
                <!ELEMENT Wheel (WheelMeshGrid, WheelDiameter, WheelWidth)>
                    <!ATTLIST Wheel driving (ДА|НЕ) #REQUIRED>
                    <!ELEMENT WheelMeshGrid (#PCDATA)>
                    <!ELEMENT WheelDiameter (#PCDATA)>
                    <!ELEMENT WheelWidth (#PCDATA)>
            <!ELEMENT Sensors (Sensor*)>
                <!ELEMENT Sensor (SensorMeshGrid, NumberOfValusPerSecond)>
                    <!ATTLIST Sensor name CDATA #REQUIRED
                                     valueType CDATA #REQUIRED>
                    <!ELEMENT SensorMeshGrid (#PCDATA)>
                    <!ELEMENT NumberOfValusPerSecond (#PCDATA)>
            <!ELEMENT Rotors (Rotor*)>
                <!ELEMENT Rotor (RotorMeshGrid, RotorLiftingPower)>
                    <!ELEMENT RotorMeshGrid (#PCDATA)>
                    <!ELEMENT RotorLiftingPower (#PCDATA)>
    <!ELEMENT Maps (Map*)>
        <!ELEMENT Map (MapData, Denivelation)>
            <!ATTLIST Map id ID #REQUIRED
                          environments IDREFS #REQUIRED>
            <!ELEMENT MapData (#PCDATA)>
            <!ELEMENT Denivelation (#PCDATA)>
    <!ELEMENT Algorithms (Algorithm*)>
        <!ELEMENT Algorithm (Complexity, Depth)>
            <!ATTLIST Algorithm id ID #REQUIRED
                                name CDATA #REQUIRED 
                                diffEnvironments (ДА|НЕ) #REQUIRED
                                multipleDestPoints (ДА|НЕ) #REQUIRED>
            <!ELEMENT Complexity (#PCDATA)>
            <!ELEMENT Depth (#PCDATA)>

=== Anton94/XML-and-ASP-programming/ASP.NET project/ValidXMLDocument-14.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RoboSimulation SYSTEM "RoboSim.dtd">
<RoboSimulation>
    <SimulationName>Симулация 14</SimulationName>
    <SimulationOwner>Георги</SimulationOwner>
    <SimulationOwnerEmail>georgi@gmail.com</SimulationOwnerEmail>
    <Environments>
        <Environment id="IDE000" name="Земя">
            <TravelCostEnter>1.2</TravelCostEnter>
            <TravelCostIn>1.1</TravelCostIn>
            <TravelCostExit>2.1</TravelCostExit>
            <Damage>0.2</Damage>
        </Environment>
        <Environment id="IDE001" name="Вода">
            <TravelCostEnter>1.4</TravelCostEnter>
            <TravelCostIn>3.4</TravelCostIn>
            <TravelCostExit>1.8</TravelCostExit>
            <Damage>1.7</Damage>
        </Environment>    
    </Environments>
    
    <Robots>
        <Robot id="IDR000" environments="IDE000 IDE001" name="Робо МИГ20" owner="Барон">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>17.0</Speed>
            <SpeedBack>16.3</SpeedBack>
            <TurningSpeed>18.0</TurningSpeed>
            <TurningSpeedBack>18.2</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>6.0</WheelDiameter>
                    <WheelWidth>1.2</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>2.5</WheelDiameter>
                    <WheelWidth>1.0</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>6.0</WheelDiameter>
                    <WheelWidth>1.2</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>7</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
        </Robot>        
        <Robot id="IDR001" environments="IDE000" name="Робо МИГ3000" owner="Миро">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>19.0</Speed>
            <SpeedBack>19.3</SpeedBack>
            <TurningSpeed>13.5</TurningSpeed>
            <TurningSpeedBack>13.2</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>6.0</WheelDiameter>
                    <WheelWidth>1.8</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>3.8</WheelDiameter>
                    <WheelWidth>1.6</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>7.8</WheelDiameter>
                    <WheelWidth>1.8</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>9</NumberOfValusPerSecond>
                </Sensor>
                <Sensor name="Сензор за измерване на разстоянието" valueType="разстояние">
                    <SensorMeshGrid>distSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>8</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>4.4</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>4.4</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh2.obj</RotorMeshGrid>
                    <RotorLiftingPower>4.4</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh3.obj</RotorMeshGrid>
                    <RotorLiftingPower>4.4</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh4.obj</RotorMeshGrid>
                    <RotorLiftingPower>8.3</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh5.obj</RotorMeshGrid>
                    <RotorLiftingPower>8.3</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh6.obj</RotorMeshGrid>
                    <RotorLiftingPower>8.3</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh7.obj</RotorMeshGrid>
                    <RotorLiftingPower>8.3</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>        
        <Robot id="IDR002" environments="IDE001" name="Робо РИБ200" owner="Силвия">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>24.2</Speed>
            <SpeedBack>24.1</SpeedBack>
            <TurningSpeed>24.0</TurningSpeed>
            <TurningSpeedBack>24.6</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>8.0</WheelDiameter>
                    <WheelWidth>2.5</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>8.0</WheelDiameter>
                    <WheelWidth>2.1</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh3.obj</WheelMeshGrid>
                    <WheelDiameter>8.0</WheelDiameter>
                    <WheelWidth>2.1</WheelWidth>
                </Wheel>
            </Wheels>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>21.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>16.9</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh2.obj</RotorMeshGrid>
                    <RotorLiftingPower>16.9</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>     
    </Robots>
    
    <Maps>
        <Map id="IDM000" environments="IDE001">
            <MapData>map000.bin</MapData>
            <Denivelation>0</Denivelation>
        </Map>
        <Map id="IDM001" environments="IDE000 IDE001">
            <MapData>map001.bin</MapData>
            <Denivelation>2</Denivelation>
        </Map>
    </Maps>
    
    <Algorithms>
        <Algorithm id="IDA000" name="А звезда" diffEnvironments="ДА" multipleDestPoints="ДА">
            <Complexity>Зависи от евристиката</Complexity>
            <Depth>26</Depth>
        </Algorithm>  
    </Algorithms>
</RoboSimulation>

=== Anton94/XML-and-ASP-programming/ASP.NET project/xmlToSql/xmlToSql/resources/ValidXMLDocument-6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RoboSimulation SYSTEM "RoboSim.dtd">
<RoboSimulation id="S0">
    <SimulationName>Симулация 6</SimulationName>
    <SimulationOwner>Валери</SimulationOwner>
    <SimulationOwnerEmail>valeri@gmail.com</SimulationOwnerEmail>
    <Environments>
        <Environment id="IDE000" name="Вода">
            <TravelCostEnter>1.0</TravelCostEnter>
            <TravelCostIn>2.0</TravelCostIn>
            <TravelCostExit>1.5</TravelCostExit>
            <Damage>0.5</Damage>
        </Environment>
        <Environment id="IDE001" name="Блато">
            <TravelCostEnter>1.0</TravelCostEnter>
            <TravelCostIn>6.0</TravelCostIn>
            <TravelCostExit>2.5</TravelCostExit>
            <Damage>2.5</Damage>
        </Environment>      
        <Environment id="IDE002" name="Земя">
            <TravelCostEnter>1.0</TravelCostEnter>
            <TravelCostIn>1.0</TravelCostIn>
            <TravelCostExit>1.0</TravelCostExit>
            <Damage>0.0</Damage>
        </Environment>   
    </Environments>
    
    <Robots>
        <Robot id="IDR000" environments="IDE000 IDE002" name="Робо М2000" owner="Мирела">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>13.6</Speed>
            <SpeedBack>16.4</SpeedBack>
            <TurningSpeed>16.5</TurningSpeed>
            <TurningSpeedBack>14.5</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>5.5</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>5.5</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>3.0</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh3.obj</WheelMeshGrid>
                    <WheelDiameter>3.0</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>7</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>3.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>3.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh2.obj</RotorMeshGrid>
                    <RotorLiftingPower>6.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh3.obj</RotorMeshGrid>
                    <RotorLiftingPower>6.0</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>
        <Robot id="IDR001" environments="IDE000 IDE001" name="Робо 60" owner="Милко">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>13.1</Speed>
            <SpeedBack>13.6</SpeedBack>
            <TurningSpeed>11.1</TurningSpeed>
            <TurningSpeedBack>11.2</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>4.5</WheelDiameter>
                    <WheelWidth>1.7</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>4.5</WheelDiameter>
                    <WheelWidth>1.7</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>3.0</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh3.obj</WheelMeshGrid>
                    <WheelDiameter>4.5</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
            </Wheels>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>13.0</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>
        <Robot id="IDR002" environments="IDE002" name="Робо МК20" owner="Фали">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>19.0</Speed>
            <SpeedBack>18.6</SpeedBack>
            <TurningSpeed>25.0</TurningSpeed>
            <TurningSpeedBack>25.4</TurningSpeedBack>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>6</NumberOfValusPerSecond>
                </Sensor>
                <Sensor name="Сензор за измерване на звука" valueType="звук">
                    <SensorMeshGrid>distSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>9</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>13.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>13.0</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>
    </Robots>
    
    <Maps>
        <Map id="IDM000" environments="IDE000 IDE001 IDE002">
            <MapData>map000.bin</MapData>
            <Denivelation>14</Denivelation>
        </Map>
        <Map id="IDM001" environments="IDE002">
            <MapData>map001.bin</MapData>
            <Denivelation>7</Denivelation>
        </Map>
    </Maps>
    
    <Algorithms>
        <Algorithm id="IDA000" name="Търсене в дълбочина" diffEnvironments="НЕ" multipleDestPoints="ДА">
            <Complexity>Линейна</Complexity>
            <Depth>22</Depth>
        </Algorithm> 
        <Algorithm id="IDA001" name="Най-бързото спускане" diffEnvironments="НЕ" multipleDestPoints="НЕ">
            <Complexity>Линейно по пътя с евристика</Complexity>
            <Depth>Нелимитирано</Depth>
        </Algorithm>      
        <Algorithm id="IDA002" name="А звезда" diffEnvironments="ДА" multipleDestPoints="ДА">
            <Complexity>Зависи от евристиката</Complexity>
            <Depth>23</Depth>
        </Algorithm>  
    </Algorithms>
</RoboSimulation>

=== Anton94/XML-and-ASP-programming/ASP.NET project/xmlToSql/xmlToSql/resources/ValidXMLDocument-11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RoboSimulation SYSTEM "RoboSim.dtd">
<RoboSimulation id="S0">
    <SimulationName>Симулация 11</SimulationName>
    <SimulationOwner>Биби</SimulationOwner>
    <SimulationOwnerEmail>bibi@gmail.com</SimulationOwnerEmail>
    <Environments>
        <Environment id="IDE000" name="Земя">
            <TravelCostEnter>1.2</TravelCostEnter>
            <TravelCostIn>1.2</TravelCostIn>
            <TravelCostExit>1.2</TravelCostExit>
            <Damage>0.1</Damage>
        </Environment>
        <Environment id="IDE001" name="Вода">
            <TravelCostEnter>1.1</TravelCostEnter>
            <TravelCostIn>3.1</TravelCostIn>
            <TravelCostExit>4.8</TravelCostExit>
            <Damage>1.7</Damage>
        </Environment>
        <Environment id="IDE002" name="Въздух">
            <TravelCostEnter>1.2</TravelCostEnter>
            <TravelCostIn>0.5</TravelCostIn>
            <TravelCostExit>0.3</TravelCostExit>
            <Damage>0.1</Damage>
        </Environment>     
    </Environments>
    
    <Robots>
        <Robot id="IDR000" environments="IDE000 IDE002" name="Робо СМ21" owner="Алекс">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>14.0</Speed>
            <SpeedBack>14.3</SpeedBack>
            <TurningSpeed>9.0</TurningSpeed>
            <TurningSpeedBack>9.2</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>1.8</WheelDiameter>
                    <WheelWidth>1.1</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>1.8</WheelDiameter>
                    <WheelWidth>1.1</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>5.0</WheelDiameter>
                    <WheelWidth>1.1</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>5</NumberOfValusPerSecond>
                </Sensor>
                <Sensor name="Сензор за измерване на разстоянието" valueType="разстояние">
                    <SensorMeshGrid>distSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>3</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
        </Robot>        
        <Robot id="IDR001" environments="IDE001 IDE002" name="Робо ИЕ132" owner="Пешо">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>29.0</Speed>
            <SpeedBack>29.3</SpeedBack>
            <TurningSpeed>20.5</TurningSpeed>
            <TurningSpeedBack>20.2</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>9.0</WheelDiameter>
                    <WheelWidth>1.2</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>9.8</WheelDiameter>
                    <WheelWidth>1.2</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>9.8</WheelDiameter>
                    <WheelWidth>1.2</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на разстоянието" valueType="разстояние">
                    <SensorMeshGrid>distSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>5</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>12.3</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>12.3</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>        
        <Robot id="IDR002" environments="IDE000 IDE001 IDE002" name="Робо О020" owner="Симеон">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>24.8</Speed>
            <SpeedBack>24.7</SpeedBack>
            <TurningSpeed>24.8</TurningSpeed>
            <TurningSpeedBack>24.7</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>3.0</WheelDiameter>
                    <WheelWidth>1.6</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>3.0</WheelDiameter>
                    <WheelWidth>1.6</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>4.0</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh3.obj</WheelMeshGrid>
                    <WheelDiameter>4.0</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на разстоянието" valueType="разстояние">
                    <SensorMeshGrid>distSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>4</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>6.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>6.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh2.obj</RotorMeshGrid>
                    <RotorLiftingPower>3.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh3.obj</RotorMeshGrid>
                    <RotorLiftingPower>3.0</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>           
        <Robot id="IDR003" environments="IDE000 IDE001" name="Робо КМ200" owner="Мони">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>21.8</Speed>
            <SpeedBack>21.8</SpeedBack>
            <TurningSpeed>21.8</TurningSpeed>
            <TurningSpeedBack>21.8</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>19.0</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>19.0</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>19.0</WheelDiameter>
                    <WheelWidth>1.1</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh3.obj</WheelMeshGrid>
                    <WheelDiameter>19.0</WheelDiameter>
                    <WheelWidth>1.1</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>18</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>12.4</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>12.4</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh2.obj</RotorMeshGrid>
                    <RotorLiftingPower>16.2</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh3.obj</RotorMeshGrid>
                    <RotorLiftingPower>16.2</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>   
    </Robots>
    
    <Maps>
        <Map id="IDM000" environments="IDE000 IDE001 IDE002">
            <MapData>map000.bin</MapData>
            <Denivelation>9.3</Denivelation>
        </Map>
    </Maps>
    
    <Algorithms>
        <Algorithm id="IDA000" name="А звезда" diffEnvironments="ДА" multipleDestPoints="НЕ">
            <Complexity>Зависи от евристиката</Complexity>
            <Depth>55</Depth>
        </Algorithm>  
    </Algorithms>
</RoboSimulation>
