=== Anton94/XML-and-ASP-programming/ASP.NET project/xmlToSql/xmlToSql/resources/RoboSim.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT RoboSimulation (SimulationName, SimulationOwner, SimulationOwnerEmail, Environments, Robots, Maps, Algorithms)>
    <!ATTLIST RoboSimulation id ID #REQUIRED >
    <!ELEMENT SimulationName (#PCDATA)>
    <!ELEMENT SimulationOwner (#PCDATA)>
    <!ELEMENT SimulationOwnerEmail (#PCDATA)>
    <!ELEMENT  Environments (Environment*)>
        <!ELEMENT Environment (TravelCostEnter, TravelCostIn, TravelCostExit, Damage)>
            <!ATTLIST Environment id ID #REQUIRED
                                  name CDATA #REQUIRED>
            <!ELEMENT TravelCostEnter (#PCDATA)>
            <!ELEMENT TravelCostIn (#PCDATA)>
            <!ELEMENT TravelCostExit (#PCDATA)>
            <!ELEMENT Damage (#PCDATA)>
    <!ELEMENT Robots (Robot*)>
        <!ELEMENT Robot (RobotMeshGrid, Speed, SpeedBack, TurningSpeed, TurningSpeedBack, Wheels?, Sensors?, Rotors?)>
            <!ATTLIST Robot id ID #REQUIRED
                            environments IDREFS #REQUIRED
                            name CDATA #REQUIRED
                            owner CDATA #REQUIRED>
            <!ELEMENT RobotMeshGrid (#PCDATA)>
            <!ELEMENT Speed (#PCDATA)>
            <!ELEMENT SpeedBack (#PCDATA)>
            <!ELEMENT TurningSpeed (#PCDATA)>
            <!ELEMENT TurningSpeedBack (#PCDATA)>            
            <!ELEMENT Wheels (Wheel*)>          
                <!ELEMENT Wheel (WheelMeshGrid, WheelDiameter, WheelWidth)>
                    <!ATTLIST Wheel driving (ДА|НЕ) #REQUIRED>
                    <!ELEMENT WheelMeshGrid (#PCDATA)>
                    <!ELEMENT WheelDiameter (#PCDATA)>
                    <!ELEMENT WheelWidth (#PCDATA)>
            <!ELEMENT Sensors (Sensor*)>
                <!ELEMENT Sensor (SensorMeshGrid, NumberOfValusPerSecond)>
                    <!ATTLIST Sensor name CDATA #REQUIRED
                                     valueType CDATA #REQUIRED>
                    <!ELEMENT SensorMeshGrid (#PCDATA)>
                    <!ELEMENT NumberOfValusPerSecond (#PCDATA)>
            <!ELEMENT Rotors (Rotor*)>
                <!ELEMENT Rotor (RotorMeshGrid, RotorLiftingPower)>
                    <!ELEMENT RotorMeshGrid (#PCDATA)>
                    <!ELEMENT RotorLiftingPower (#PCDATA)>
    <!ELEMENT Maps (Map*)>
        <!ELEMENT Map (MapData, Denivelation)>
            <!ATTLIST Map id ID #REQUIRED
                          environments IDREFS #REQUIRED>
            <!ELEMENT MapData (#PCDATA)>
            <!ELEMENT Denivelation (#PCDATA)>
    <!ELEMENT Algorithms (Algorithm*)>
        <!ELEMENT Algorithm (Complexity, Depth)>
            <!ATTLIST Algorithm id ID #REQUIRED
                                name CDATA #REQUIRED 
                                diffEnvironments (ДА|НЕ) #REQUIRED
                                multipleDestPoints (ДА|НЕ) #REQUIRED>
            <!ELEMENT Complexity (#PCDATA)>
            <!ELEMENT Depth (#PCDATA)>

=== Anton94/XML-and-ASP-programming/ASP.NET project/ValidXMLDocument-8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RoboSimulation SYSTEM "RoboSim.dtd">
<RoboSimulation id="S0" name="Симулация 8" owner="Влашко">
    <SimulationOwnerEmail>antonvdudov@gmail.com</SimulationOwnerEmail>
    <SimulationDescription>Описание на симулация 8</SimulationDescription>
    <SimulationRating>2.5</SimulationRating>
    <Environments>
        <Environment id="IDE000" name="Земя">
            <TravelCostEnter>1.0</TravelCostEnter>
            <TravelCostIn>1.0</TravelCostIn>
            <TravelCostExit>1.0</TravelCostExit>
            <Damage>0.0</Damage>
        </Environment>
    </Environments>
    
    <Robots>
        <Robot id="IDR000" name="Робо КЯМ13" owner="Юли">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>22.6</Speed>
            <SpeedBack>22.3</SpeedBack>
            <TurningSpeed>22.0</TurningSpeed>
            <TurningSpeedBack>22.1</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>2.5</WheelDiameter>
                    <WheelWidth>3.8</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>2.5</WheelDiameter>
                    <WheelWidth>2.8</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>4.0</WheelDiameter>
                    <WheelWidth>1.8</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>2</NumberOfValusPerSecond>
                </Sensor>
                <Sensor name="Сензор за измерване на разстоянието" valueType="разстояние">
                    <SensorMeshGrid>distSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>7</NumberOfValusPerSecond>
                </Sensor>
                <Sensor name="Сензор за измерване на звука" valueType="звук">
                    <SensorMeshGrid>distSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>3</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
        </Robot>                
        <Robot id="IDR001" name="Робо САЯ12" owner="Габи">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>23.0</Speed>
            <SpeedBack>23.3</SpeedBack>
            <TurningSpeed>23.0</TurningSpeed>
            <TurningSpeedBack>23.3</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>12.0</WheelDiameter>
                    <WheelWidth>4.4</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>12.0</WheelDiameter>
                    <WheelWidth>4.4</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>15.0</WheelDiameter>
                    <WheelWidth>4.4</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh3.obj</WheelMeshGrid>
                    <WheelDiameter>15.0</WheelDiameter>
                    <WheelWidth>4.4</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на разстоянието" valueType="разстояние">
                    <SensorMeshGrid>distSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>8</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
        </Robot>          
        <Robot id="IDR002" name="Робо ЛНС12" owner="Петър">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>19.0</Speed>
            <SpeedBack>19.6</SpeedBack>
            <TurningSpeed>18.0</TurningSpeed>
            <TurningSpeedBack>19.1</TurningSpeedBack>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>13</NumberOfValusPerSecond>
                </Sensor>
                <Sensor name="Сензор за измерване на разстоянието" valueType="разстояние">
                    <SensorMeshGrid>distSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>9</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>31.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>31.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh2.obj</RotorMeshGrid>
                    <RotorLiftingPower>36.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh3.obj</RotorMeshGrid>
                    <RotorLiftingPower>36.0</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>
        
        <Robot id="IDR003" name="Робо ШЯВС13" owner="Васко">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>14.2</Speed>
            <SpeedBack>14.7</SpeedBack>
            <TurningSpeed>14.0</TurningSpeed>
            <TurningSpeedBack>14.2</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>6.0</WheelDiameter>
                    <WheelWidth>3.6</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>6.0</WheelDiameter>
                    <WheelWidth>3.6</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>16</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>4.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>4.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh2.obj</RotorMeshGrid>
                    <RotorLiftingPower>7.5</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh3.obj</RotorMeshGrid>
                    <RotorLiftingPower>7.5</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot> 
    </Robots>
    
    <Maps>
        <Map id="IDM000" name="Карта 1">
            <MapData>map000.bin</MapData>
            <Denivelation>3.1</Denivelation>
        </Map>
        <Map id="IDM001" name="Карта 2">
            <MapData>map001.bin</MapData>
            <Denivelation>4.2</Denivelation>
        </Map>
        <Map id="IDM002" name="Карта 3">
            <MapData>map002.bin</MapData>
            <Denivelation>2.7</Denivelation>
        </Map>
        <Map id="IDM003" name="Карта 4">
            <MapData>map003.bin</MapData>
            <Denivelation>5.9</Denivelation>
        </Map>
        <Map id="IDM004" name="Карта 5">
            <MapData>map004.bin</MapData>
            <Denivelation>1.5</Denivelation>
        </Map>
        <Map id="IDM005" name="Карта 6">
            <MapData>map005.bin</MapData>
            <Denivelation>0</Denivelation>
        </Map>
    </Maps>
    
    <Algorithms>
        <Algorithm id="IDA000" name="Търсене в ширина" diffEnvironments="НЕ" multipleDestPoints="ДА">
            <Complexity>Линейна</Complexity>
            <Depth>45</Depth>
        </Algorithm>
        <Algorithm id="IDA001" name="Търсене в дълбочина" diffEnvironments="НЕ" multipleDestPoints="НЕ">
            <Complexity>Линейна</Complexity>
            <Depth>45</Depth>
        </Algorithm> 
        <Algorithm id="IDA002" name="Най-бързото спускане" diffEnvironments="НЕ" multipleDestPoints="НЕ">
            <Complexity>Линейно по пътя с евристика</Complexity>
            <Depth>Нелимитирано</Depth>
        </Algorithm>      
    </Algorithms>
</RoboSimulation>

=== Anton94/XML-and-ASP-programming/ASP.NET project/ValidXMLDocument-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RoboSimulation SYSTEM "RoboSim.dtd">
<RoboSimulation>
    <SimulationName>Симулация 3</SimulationName>
    <SimulationOwner>Петър</SimulationOwner>
    <SimulationOwnerEmail>petur@gmail.com</SimulationOwnerEmail>
    <Environments>
        <Environment id="IDE000" name="Земя">
            <TravelCostEnter>1.0</TravelCostEnter>
            <TravelCostIn>1.0</TravelCostIn>
            <TravelCostExit>1.0</TravelCostExit>
            <Damage>0.0</Damage>
        </Environment>
        <Environment id="IDE001" name="Вода">
            <TravelCostEnter>1.6</TravelCostEnter>
            <TravelCostIn>2.1</TravelCostIn>
            <TravelCostExit>1.8</TravelCostExit>
            <Damage>1.5</Damage>
        </Environment>
        <Environment id="IDE002" name="Въздух">
            <TravelCostEnter>1.2</TravelCostEnter>
            <TravelCostIn>0.6</TravelCostIn>
            <TravelCostExit>0.0</TravelCostExit>
            <Damage>0.0</Damage>
        </Environment>     
    </Environments>
    
    <Robots>
        <Robot id="IDR000" environments="IDE000 IDE001" name="Робо A4000" owner="Иван">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>13.0</Speed>
            <SpeedBack>13.3</SpeedBack>
            <TurningSpeed>8.0</TurningSpeed>
            <TurningSpeedBack>8.2</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>1.5</WheelDiameter>
                    <WheelWidth>1.0</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>1.5</WheelDiameter>
                    <WheelWidth>1.0</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>2.0</WheelDiameter>
                    <WheelWidth>1.0</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>5</NumberOfValusPerSecond>
                </Sensor>
                <Sensor name="Сензор за измерване на разстоянието" valueType="разстояние">
                    <SensorMeshGrid>distSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>5</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
        </Robot>        
        <Robot id="IDR001" environments="IDE000 IDE002" name="Робо Б4000" owner="Мартин">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>19.0</Speed>
            <SpeedBack>19.3</SpeedBack>
            <TurningSpeed>10.5</TurningSpeed>
            <TurningSpeedBack>10.2</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>5.0</WheelDiameter>
                    <WheelWidth>1.2</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>2.8</WheelDiameter>
                    <WheelWidth>1.2</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>2.8</WheelDiameter>
                    <WheelWidth>1.2</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>5</NumberOfValusPerSecond>
                </Sensor>
                <Sensor name="Сензор за измерване на разстоянието" valueType="разстояние">
                    <SensorMeshGrid>distSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>5</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>2.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>2.0</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>        
        <Robot id="IDR002" environments="IDE000 IDE001 IDE002" name="Робо В4000" owner="Иван">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>24.2</Speed>
            <SpeedBack>24.1</SpeedBack>
            <TurningSpeed>24.0</TurningSpeed>
            <TurningSpeedBack>24.6</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>3.0</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>3.0</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>4.0</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh3.obj</WheelMeshGrid>
                    <WheelDiameter>4.0</WheelDiameter>
                    <WheelWidth>1.3</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на разстоянието" valueType="разстояние">
                    <SensorMeshGrid>distSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>5</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>2.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>2.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh2.obj</RotorMeshGrid>
                    <RotorLiftingPower>1.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh3.obj</RotorMeshGrid>
                    <RotorLiftingPower>1.0</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>           
        <Robot id="IDR003" environments="IDE002" name="Робо Г4000" owner="Тони">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>32.0</Speed>
            <SpeedBack>30.8</SpeedBack>
            <TurningSpeed>26.25</TurningSpeed>
            <TurningSpeedBack>28.2</TurningSpeedBack>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>5</NumberOfValusPerSecond>
                </Sensor>
                <Sensor name="Сензор за измерване на разстоянието" valueType="разстояние">
                    <SensorMeshGrid>distSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>5</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
            <Rotors>
                <Rotor>
                    <RotorMeshGrid>RotorMesh0.obj</RotorMeshGrid>
                    <RotorLiftingPower>5.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh1.obj</RotorMeshGrid>
                    <RotorLiftingPower>5.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh2.obj</RotorMeshGrid>
                    <RotorLiftingPower>6.0</RotorLiftingPower>
                </Rotor>
                <Rotor>
                    <RotorMeshGrid>RotorMesh3.obj</RotorMeshGrid>
                    <RotorLiftingPower>6.0</RotorLiftingPower>
                </Rotor>
            </Rotors>
        </Robot>   
    </Robots>
    
    <Maps>
        <Map id="IDM000" environments="IDE000 IDE001 IDE002">
            <MapData>map000.bin</MapData>
            <Denivelation>15</Denivelation>
        </Map>
    </Maps>
    
    <Algorithms>
        <Algorithm id="IDA000" name="А звезда" diffEnvironments="ДА" multipleDestPoints="НЕ">
            <Complexity>Зависи от евристиката</Complexity>
            <Depth>35</Depth>
        </Algorithm>  
    </Algorithms>
</RoboSimulation>

=== Anton94/XML-and-ASP-programming/ASP.NET project/ValidXMLDocument-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RoboSimulation SYSTEM "RoboSim.dtd">
<RoboSimulation>
    <SimulationName>Симулация 1</SimulationName>
    <SimulationOwner>Антон</SimulationOwner>
    <SimulationOwnerEmail>antonvdudov@gmail.com</SimulationOwnerEmail>
    <Environments>
        <Environment id="IDE000" name="Земя">
            <TravelCostEnter>1.0</TravelCostEnter>
            <TravelCostIn>1.0</TravelCostIn>
            <TravelCostExit>1.0</TravelCostExit>
            <Damage>0.0</Damage>
        </Environment>
        <Environment id="IDE001" name="Вода">
            <TravelCostEnter>1.0</TravelCostEnter>
            <TravelCostIn>2.0</TravelCostIn>
            <TravelCostExit>1.5</TravelCostExit>
            <Damage>0.5</Damage>
        </Environment>
        <Environment id="IDE002" name="Блато">
            <TravelCostEnter>1.0</TravelCostEnter>
            <TravelCostIn>4.0</TravelCostIn>
            <TravelCostExit>2.5</TravelCostExit>
            <Damage>2.0</Damage>
        </Environment>         
    </Environments>
    
    <Robots>
        <Robot id="IDR000" environments="IDE000 IDE001 IDE002" name="Робо A2000" owner="Тони">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>10</Speed>
            <SpeedBack>10</SpeedBack>
            <TurningSpeed>6</TurningSpeed>
            <TurningSpeedBack>6</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>0.5</WheelDiameter>
                    <WheelWidth>0.5</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>0.5</WheelDiameter>
                    <WheelWidth>0.5</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>5</NumberOfValusPerSecond>
                </Sensor>
                <Sensor name="Сензор за измерване на разстоянието" valueType="разстояние">
                    <SensorMeshGrid>distSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>5</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
        </Robot>
        <Robot id="IDR001" environments="IDE000 IDE001 IDE002" name="Робо Б2000" owner="Антон">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>20</Speed>
            <SpeedBack>10</SpeedBack>
            <TurningSpeed>16</TurningSpeed>
            <TurningSpeedBack>6</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>1.5</WheelDiameter>
                    <WheelWidth>0.5</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>1.5</WheelDiameter>
                    <WheelWidth>0.5</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>0.5</WheelDiameter>
                    <WheelWidth>0.5</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на разстоянието" valueType="разстояние">
                    <SensorMeshGrid>distSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>5</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
        </Robot>
        <Robot id="IDR002" environments="IDE000" name="Робо В2000" owner="Мавро">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>30</Speed>
            <SpeedBack>13</SpeedBack>
            <TurningSpeed>26</TurningSpeed>
            <TurningSpeedBack>26</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>2.0</WheelDiameter>
                    <WheelWidth>1.5</WheelWidth>
                </Wheel>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>2.0</WheelDiameter>
                    <WheelWidth>1.5</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на разстоянието" valueType="разстояние">
                    <SensorMeshGrid>distSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>5</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
        </Robot>
        <Robot id="IDR003" environments="IDE001" name="Робо Г2000" owner="Бойко">
            <RobotMeshGrid>mesh.obj</RobotMeshGrid>
            <Speed>13</Speed>
            <SpeedBack>14</SpeedBack>
            <TurningSpeed>10</TurningSpeed>
            <TurningSpeedBack>16</TurningSpeedBack>
            <Wheels>
                <Wheel driving="ДА">
                    <WheelMeshGrid>wheelMesh0.obj</WheelMeshGrid>
                    <WheelDiameter>2.0</WheelDiameter>
                    <WheelWidth>1.5</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh1.obj</WheelMeshGrid>
                    <WheelDiameter>1.0</WheelDiameter>
                    <WheelWidth>1.5</WheelWidth>
                </Wheel>
                <Wheel driving="НЕ">
                    <WheelMeshGrid>wheelMesh2.obj</WheelMeshGrid>
                    <WheelDiameter>1.0</WheelDiameter>
                    <WheelWidth>1.5</WheelWidth>
                </Wheel>
            </Wheels>
            <Sensors>
                <Sensor name="Сензор за измерване на топлината" valueType="топлина">
                    <SensorMeshGrid>tempSensorMesh.obj</SensorMeshGrid>
                    <NumberOfValusPerSecond>5</NumberOfValusPerSecond>
                </Sensor>
            </Sensors>
        </Robot>
    </Robots>
    
    <Maps>
        <Map id="IDM000" environments="IDE000 IDE001 IDE002">
            <MapData>map000.bin</MapData>
            <Denivelation>10</Denivelation>
        </Map>
        <Map id="IDM001" environments="IDE001 IDE002">
            <MapData>map001.bin</MapData>
            <Denivelation>0</Denivelation>
        </Map>
        <Map id="IDM002" environments="IDE001 IDE002">
            <MapData>map002.bin</MapData>
            <Denivelation>10</Denivelation>
        </Map>
        <Map id="IDM003" environments="IDE002">
            <MapData>map003.bin</MapData>
            <Denivelation>5</Denivelation>
        </Map>
    </Maps>
   
    <Algorithms>
        <Algorithm id="IDA000" name="Търсене в ширина" diffEnvironments="НЕ" multipleDestPoints="ДА">
            <Complexity>Линейна</Complexity>
            <Depth>20</Depth>
        </Algorithm>
        <Algorithm id="IDA001" name="Търсене в дълбочина" diffEnvironments="НЕ" multipleDestPoints="ДА">
            <Complexity>Линейна</Complexity>
            <Depth>20</Depth>
        </Algorithm>
        <Algorithm id="IDA002" name="А звезда" diffEnvironments="ДА" multipleDestPoints="ДА">
            <Complexity>Зависи от евристиката</Complexity>
            <Depth>20</Depth>
        </Algorithm>        
    </Algorithms>
</RoboSimulation>
